/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hitesh_qualtemp_MyNDK */

//This is the class generated after the ndk is built

#ifndef _Included_com_example_hitesh_qualtemp_MyNDK
#define _Included_com_example_hitesh_qualtemp_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hitesh_qualtemp_MyNDK
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_hitesh_qualtemp_MyNDK_getMyString (JNIEnv *, jobject, jint );




#ifdef __cplusplus
}
#endif
#endif

